### ISSUE TITLE
Guide not installing completely from plugin store or project config sync

### ISSUE THREAD

**Issue by TheFunkyMonk** [wbrowar/craft-guide#49]
## Description

This plugin seems to not fully being installed/initialized from the plugin store (or other environments via project config sync).

## Steps to Reproduce
1. Install Guide plugin (Lite version) from the Craft Plugin Store

### Expected Behavior
Guide shows up as a sidebar item and is shown as "Installed" under Settings > Plugins

### Actual Behavior
Guide does not show up as a sidebar item and is shown as "Not Installed" under Settings > Plugins

## Additional Information

If you select the menu option to install Guide under the Settings > Plugins list, it successfully installs and you're taken to a welcome screen for the plugin where you click a button to continue to setup. I did not see this welcome screen when installing from the plugin store, so seems maybe there's something necessary happening when the welcome screen is displayed and interacted with that's not happening on initial install.

## Versions
Craft CMS: 3.7.12
Guide: 3.1.0
MySQL 5.7.32

**Comment by wbrowar** [comment]
Thanks for all of the detail, @TheFunkyMonk. I'll take a look and see if there's something going on.

**Comment by KatieMFritz** [comment]
I'm having a similar issue. Some weird things happened when I installed locally from the plugin store, but I didn't record them. 😬 

But when I do a normal deployment process to staging, the plugin isn't getting installed. 

Steps to reproduce (Craft Pro 3.7.27.2)
1. Install Guide locally and confirm it's working. Commit changes. 
2. Push code to staging server.
3. `composer install` (no errors)
4. `./craft migrate/all` (no errors)
5. `./craft project-config/apply` (no errors)

When I look in my applied project config from the staging site Utilities section, I see the following:
```
guide:
    edition: pro
    enabled: true
    licenseKey: redacted
    schemaVersion: 3.0.0
    settings:
      assetVolume: eb279ad8-235a-4e19-b591-e353e547e7af
      clientName: `redacted`
      defaultTeleportMethod: append
      myCompanyName: 'Foster Commerce'
      projectName: 'redacted'
      templatePath: _guide
```
